esphome:
  name: atom-s3
  friendly_name: Atom S3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

substitutions:
  display_rotation: "180" # Options: 0, 90, 180, 270
  font_family: "gfonts://Roboto"
  font_size: "26"
  text_align: "TextAlign::CENTER"
  text_x_position: "it.get_width() / 2"
  text_y_position: "it.get_height() / 2 + 35"
  icon_x_position: "it.get_width() / 2"
  icon_y_position: "it.get_height() / 2 - 15"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "PKH366LU6sUzsX/6h7U+GlYF1D1gbKNyDE17rDDKlp0="
web_server:
  port: 80
captive_portal:  # This component automatically enables OTA

ota:
  - platform: esphome
    password: "efe76fdf71a975279e77443f87c383bb"

globals:
  - id: bg_red
    type: float
    initial_value: '1.0'
  - id: bg_green
    type: float
    initial_value: '1.0'
  - id: bg_blue
    type: float
    initial_value: '1.0'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Required for the display to communicate
spi:
  clk_pin: 17   # SCK -> G17
  mosi_pin: 21  # MOSI -> G21

# Load fonts
font:
  # Main text font
  - file: "gfonts://Roboto"
    id: my_font
    size: 26

  # Material Design Icons font with specific glyphs
  # Note: Glyphs list MUST match all icons defined in mapping entries
  - file: "gfonts://Material+Icons"
    id: icon_font
    size: 50
    glyphs:
      # Lighting
      - "\U0000e88a"  # home
      - "\U0000e0f0"  # lightbulb
      - "\U0000e90f"  # lightbulb_outline
      - "\U0000ef52"  # highlight_alt
      - "\U0000e1ac"  # brightness_high
      # Climate
      - "\U0000e1ff"  # device_thermostat
      - "\U0000e80e"  # whatshot
      - "\U0000ebd3"  # severe_cold
      - "\U0000ec0c"  # wind_power
      - "\U0000eb3b"  # ac_unit
      - "\U0000f076"  # thermostat (heater)
      # Water & Weather
      - "\U0000e798"  # water_drop
      - "\U0000e430"  # wb_sunny
      - "\U0000e2bd"  # cloud
      - "\U0000ea46"  # nights_stay
      - "\U0000e42d"  # wb_cloudy
      # Power
      - "\U0000e63c"  # flash_on
      - "\U0000e1a4"  # battery_full
      - "\U0000e19c"  # battery_alert
      - "\U0000ec0f"  # solar_power
      # Security
      - "\U0000e897"  # lock
      - "\U0000e898"  # lock_open
      - "\U0000e32a"  # security
      - "\U0000e3b0"  # camera_alt
      - "\U0000e566"  # directions_run
      - "\U0000e855"  # alarm
      - "\U0000e9e0"  # shield
      # Doors & Windows
      - "\U0000f1b5"  # sensor_door
      - "\U0000eb4f"  # meeting_room
      - "\U0000f088"  # window
      - "\U0000e885"  # garage
      # Rooms
      - "\U0000eb47"  # kitchen
      - "\U0000ea48"  # single_bed
      - "\U0000efdd"  # bathroom
      - "\U0000e42a"  # view_comfortable
      - "\U0000e8f9"  # work
      # Furniture & Appliances
      - "\U0000efed"  # chair
      - "\U0000efdf"  # bed
      - "\U0000e333"  # tv
      - "\U0000e30a"  # computer
      - "\U0000e32f"  # tablet
      # Audio & Media
      - "\U0000e32d"  # speaker
      - "\U0000e405"  # music_note
      - "\U0000e050"  # volume_up
      - "\U0000e029"  # mic
      - "\U0000e310"  # headset
      - "\U0000e03e"  # radio
      # Appliances
      - "\U0000f1b1"  # wash
      - "\U0000f1b3"  # dry
      - "\U0000e541"  # local_cafe
      - "\U0000f204"  # microwave
      # Outdoor
      - "\U0000ea79"  # agriculture
      - "\U0000ea99"  # forest
      - "\U0000ea47"  # outdoor_grill
      - "\U0000eb48"  # pool
      # Transport
      - "\U0000e531"  # directions_car
      - "\U0000e52f"  # directions_bike
      - "\U0000e530"  # directions_bus
      - "\U0000e570"  # train
      - "\U0000e195"  # airplanemode_active
      # Connectivity
      - "\U0000e63e"  # wifi
      - "\U0000e1a7"  # bluetooth
      - "\U0000e0cd"  # phone
      - "\U0000e80b"  # public
      - "\U0000e307"  # cast
      # Notifications
      - "\U0000e7f4"  # notifications
      - "\U0000e002"  # warning
      - "\U0000e88e"  # info
      - "\U0000e000"  # error
      # Actions
      - "\U0000e037"  # play_arrow
      - "\U0000e034"  # pause
      - "\U0000e047"  # stop
      - "\U0000e8b8"  # settings
      - "\U0000e5d3"  # more_horiz
      - "\U0000e5ca"  # check
      - "\U0000e5cd"  # close
      - "\U0000e145"  # add
      - "\U0000e15b"  # remove
      # Sensors
      - "\U0000eb4a"  # smoke_free
      - "\U0000e7b0"  # co2
      # Time
      - "\U0000e924"  # watch_later
      - "\U0000e425"  # timer
      - "\U0000e935"  # calendar_today
      - "\U0000e8b5"  # schedule
      # Entertainment
      - "\U0000e30f"  # gamepad
      - "\U0000e02c"  # movie
      - "\U0000ea30"  # sports
      - "\U0000e865"  # book
      - "\U0000e410"  # photo
      # Utilities
      - "\U0000e872"  # delete
      - "\U0000e760"  # recycling
      - "\U0000e152"  # filter_list
      - "\U0000e869"  # build
      - "\U0000f100"  # home_repair_service
      # Finance
      - "\U0000e6e1"  # show_chart

# Define the display
display:
  - platform: st7789v
    id: display_1
    model: CUSTOM
    cs_pin: 15      # CS -> G15
    dc_pin: 33      # DC/RS -> G33
    reset_pin: 34   # RST -> G34 (note: some GPIO34 pins are input-only on some chips)
    rotation: ${display_rotation}
    width: 128
    height: 128
    offset_height: 3
    offset_width: 1
    lambda: |-
      // Get friendly name from select and lookup unicode glyph from mapping
      auto icon_option = id(display_icon).state;
      const char* icon_char = id(icon_map)[icon_option.c_str()].c_str();
      
      if (id(screen_colors).current_values.is_on()) {
        // Light is ON -> Use the color from globals
        auto bg_color = Color(id(bg_red) * 255, id(bg_green) * 255, id(bg_blue) * 255);
        // Set text/icon color based on background brightness for contrast
        auto fg_color = (id(bg_red) * 0.299 + id(bg_green) * 0.587 + id(bg_blue) * 0.114) > 0.5 ? Color(0, 0, 0) : Color(255, 255, 255);
        it.fill(bg_color);
        
        // Draw icon
        it.printf($icon_x_position, $icon_y_position, id(icon_font), fg_color, TextAlign::CENTER, "%s", icon_char);
        
        // Draw text
        it.printf($text_x_position, $text_y_position, id(my_font), fg_color, $text_align, "%s", id(display_text).state.c_str());
      } else {
        // Light is OFF -> Black background, white text/icon
        it.fill(Color(0, 0, 0));
        
        // Draw icon
        it.printf($icon_x_position, $icon_y_position, id(icon_font), Color(255, 255, 255), TextAlign::CENTER, "%s", icon_char);
        
        // Draw text
        it.printf($text_x_position, $text_y_position, id(my_font), Color(255, 255, 255), $text_align, "%s", id(display_text).state.c_str());
      }

# Built-in Button (on GPIO 41, which is the screen itself)
binary_sensor:
  - platform: gpio
    pin: 
      number: 41
      inverted: true
      mode:
        input: true
        pullup: true
    name: "AtomS3 Button"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log: "Button Pressed!"
        - light.toggle: screen_colors
    on_release:
      then:
        - logger.log: "Button Released!"

# Virtual outputs to connect the RGB light to our globals
output:
  - platform: ledc
    pin: 16 # LCD_BL -> G16
    id: backlight_output
    frequency: 1000 Hz
  - platform: template
    id: red_output
    type: float
    write_action:
      - lambda: |-
          id(bg_red) = state;
  - platform: template
    id: green_output
    type: float
    write_action:
      - lambda: |-
          id(bg_green) = state;
  - platform: template
    id: blue_output
    type: float
    write_action:
      - lambda: |-
          id(bg_blue) = state;
          id(display_1).update();

# Virtual RGB light that controls the outputs
light:
  - platform: monochromatic
    name: "Screen Backlight"
    id: screen_backlight
    output: backlight_output
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_ON
  - platform: rgb
    name: "Screen Colors"
    id: screen_colors
    red: red_output
    green: green_output
    blue: blue_output
text:
  - platform: template
    name: "Display Text"
    id: display_text
    initial_value: "Hello!"
    optimistic: true
    mode: text
    on_value:
      then:
        - component.update: display_1

# Mapping component: Maps friendly names to unicode glyphs
mapping:
  - id: icon_map
    from: string
    to: string
    entries:
      # Lighting
      "Home": "\U0000e88a"              # home
      "Light On": "\U0000e0f0"          # lightbulb
      "Light Off": "\U0000e90f"         # lightbulb_outline
      "Lamp": "\U0000ef52"              # highlight_alt
      "Brightness": "\U0000e1ac"        # brightness_high

      # Climate control
      "Thermometer": "\U0000e1ff"       # device_thermostat
      "Hot": "\U0000e80e"               # whatshot
      "Cold": "\U0000ebd3"              # severe_cold
      "Fan": "\U0000ec0c"               # wind_power
      "AC": "\U0000eb3b"                # ac_unit
      "Heater": "\U0000f076"            # thermostat

      # Water & Weather
      "Water": "\U0000e798"             # water_drop
      "Rain": "\U0000e2bd"              # cloud
      "Sunny": "\U0000e430"             # wb_sunny
      "Moon": "\U0000ea46"              # nights_stay
      "Weather": "\U0000e42d"           # wb_cloudy

      # Power & Energy
      "Power": "\U0000e63c"             # flash_on
      "Battery": "\U0000e1a4"           # battery_full
      "Battery Low": "\U0000e19c"       # battery_alert
      "Solar": "\U0000ec0f"             # solar_power

      # Security
      "Lock": "\U0000e897"              # lock
      "Unlock": "\U0000e898"            # lock_open
      "Security": "\U0000e32a"          # security
      "Camera": "\U0000e3b0"            # camera_alt
      "Motion": "\U0000e566"            # directions_run
      "Alarm": "\U0000e855"             # alarm
      "Shield": "\U0000e9e0"            # shield

      # Doors & Windows
      "Door": "\U0000f1b5"              # sensor_door
      "Door Open": "\U0000eb4f"         # meeting_room
      "Window": "\U0000f088"            # window
      "Garage Door": "\U0000e885"       # garage

      # Rooms
      "Kitchen": "\U0000eb47"           # kitchen
      "Bedroom": "\U0000ea48"           # single_bed
      "Bathroom": "\U0000efdd"          # bathroom
      "Living Room": "\U0000e42a"       # view_comfortable
      "Office": "\U0000e8f9"            # work
      "Garage": "\U0000e885"            # garage

      # Furniture & Appliances
      "Chair": "\U0000efed"             # chair
      "Bed": "\U0000efdf"               # bed
      "TV": "\U0000e333"                # tv
      "Computer": "\U0000e30a"          # computer
      "Tablet": "\U0000e32f"            # tablet

      # Audio & Media
      "Speaker": "\U0000e32d"           # speaker
      "Music": "\U0000e405"             # music_note
      "Volume": "\U0000e050"            # volume_up
      "Microphone": "\U0000e029"        # mic
      "Headphones": "\U0000e310"        # headset
      "Radio": "\U0000e03e"             # radio

      # Appliances
      "Washer": "\U0000f1b1"            # wash
      "Dryer": "\U0000f1b3"             # dry
      "Coffee": "\U0000e541"            # local_cafe
      "Microwave": "\U0000f204"         # microwave
      "Fridge": "\U0000eb47"            # kitchen

      # Outdoor
      "Garden": "\U0000ea79"            # agriculture
      "Tree": "\U0000ea99"              # forest
      "BBQ": "\U0000ea47"               # outdoor_grill
      "Pool": "\U0000eb48"              # pool
      "Sprinkler": "\U0000e798"         # water_drop

      # Transport
      "Car": "\U0000e531"               # directions_car
      "Bike": "\U0000e52f"              # directions_bike
      "Bus": "\U0000e530"               # directions_bus
      "Train": "\U0000e570"             # train
      "Airplane": "\U0000e195"          # airplanemode_active

      # Connectivity
      "WiFi": "\U0000e63e"              # wifi
      "Bluetooth": "\U0000e1a7"         # bluetooth
      "Phone": "\U0000e0cd"             # phone
      "Network": "\U0000e80b"           # public
      "Cast": "\U0000e307"              # cast

      # Notifications & Alerts
      "Notification": "\U0000e7f4"      # notifications
      "Alert": "\U0000e002"             # warning
      "Info": "\U0000e88e"              # info
      "Error": "\U0000e000"             # error

      # Actions & Controls
      "Play": "\U0000e037"              # play_arrow
      "Pause": "\U0000e034"             # pause
      "Stop": "\U0000e047"              # stop
      "Settings": "\U0000e8b8"          # settings
      "More": "\U0000e5d3"              # more_horiz
      "Check": "\U0000e5ca"             # check
      "Close": "\U0000e5cd"             # close
      "Add": "\U0000e145"               # add
      "Remove": "\U0000e15b"            # remove

      # Sensors
      "Temperature": "\U0000e1ff"       # device_thermostat
      "Smoke": "\U0000eb4a"             # smoke_free
      "CO2": "\U0000e7b0"               # co2

      # Time & Schedule
      "Clock": "\U0000e924"             # watch_later
      "Timer": "\U0000e425"             # timer
      "Alarm Clock": "\U0000e855"       # alarm
      "Calendar": "\U0000e935"          # calendar_today
      "Schedule": "\U0000e8b5"          # schedule

      # Entertainment
      "Gaming": "\U0000e30f"            # gamepad
      "Movie": "\U0000e02c"             # movie
      "Sports": "\U0000ea30"            # sports
      "Book": "\U0000e865"              # book
      "Photo": "\U0000e410"             # photo

      # Utilities
      "Trash": "\U0000e872"             # delete
      "Recycle": "\U0000e760"           # recycling
      "Filter": "\U0000e152"            # filter_list
      "Tools": "\U0000e869"             # build
      "Repair": "\U0000f100"            # home_repair_service

      # Finance
      "Stock": "\U0000e6e1"             # show_chart

select:
  - platform: template
    name: "Display Icon"
    id: display_icon
    optimistic: true
    initial_option: "Home"
    options:
      # Lighting
      - "Home"
      - "Light On"
      - "Light Off"
      - "Lamp"
      - "Brightness"
      # Climate
      - "Thermometer"
      - "Hot"
      - "Cold"
      - "Fan"
      - "AC"
      - "Heater"
      # Water & Weather
      - "Water"
      - "Rain"
      - "Sunny"
      - "Moon"
      - "Weather"
      # Power
      - "Power"
      - "Battery"
      - "Battery Low"
      - "Solar"
      # Security
      - "Lock"
      - "Unlock"
      - "Security"
      - "Camera"
      - "Motion"
      - "Alarm"
      - "Shield"
      # Doors & Windows
      - "Door"
      - "Door Open"
      - "Window"
      - "Garage Door"
      # Rooms
      - "Kitchen"
      - "Bedroom"
      - "Bathroom"
      - "Living Room"
      - "Office"
      - "Garage"
      # Furniture
      - "Chair"
      - "Bed"
      - "TV"
      - "Computer"
      - "Tablet"
      # Audio & Media
      - "Speaker"
      - "Music"
      - "Volume"
      - "Microphone"
      - "Headphones"
      - "Radio"
      # Appliances
      - "Washer"
      - "Dryer"
      - "Coffee"
      - "Microwave"
      - "Fridge"
      # Outdoor
      - "Garden"
      - "Tree"
      - "BBQ"
      - "Pool"
      - "Sprinkler"
      # Transport
      - "Car"
      - "Bike"
      - "Bus"
      - "Train"
      - "Airplane"
      # Connectivity
      - "WiFi"
      - "Bluetooth"
      - "Phone"
      - "Network"
      - "Cast"
      # Notifications
      - "Notification"
      - "Alert"
      - "Info"
      - "Error"
      # Actions
      - "Play"
      - "Pause"
      - "Stop"
      - "Settings"
      - "More"
      - "Check"
      - "Close"
      - "Add"
      - "Remove"
      # Sensors
      - "Temperature"
      - "Smoke"
      - "CO2"
      # Time
      - "Clock"
      - "Timer"
      - "Alarm Clock"
      - "Calendar"
      - "Schedule"
      # Entertainment
      - "Gaming"
      - "Movie"
      - "Sports"
      - "Book"
      - "Photo"
      # Utilities
      - "Trash"
      - "Recycle"
      - "Filter"
      - "Tools"
      - "Repair"
      # Finance
      - "Stock"
    on_value:
      then:
        - component.update: display_1
sensor:
  - platform: template
    name: "Display Rotation"
    id: display_rotation_sensor
    unit_of_measurement: "°"
    update_interval: never
    lambda: |-
      return ${display_rotation};
