substitutions:
  device_id: timer-camera-f
  device_label: Timer Cam F
  cam_label: Cam
  led_label: LED

esphome:
  name: ${device_id}
  friendly_name: ${device_label}

  on_boot:
    priority: 600
    then:
      - bm8563.read_time: {}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# PSRAM required for camera
psram:
  mode: quad
  speed: 80MHz

# Networking + OTA + API
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  ap:
    ssid: "TimerCamera-F Fallback"
    password: "HZruGeKzRAfh"

logger:

api:
  encryption:
    key: "7JFTWl/7SOz11JinNgajCK88Lu05aTew2D60iRoxpAQ="

ota:
  platform: esphome
  password: "b05ede71a13e4841f6805539b579fdfe"

captive_portal:

# I2C buses (RTC + camera SCCB)
i2c:
  - id: bsp_i2c
    sda: GPIO12
    scl: GPIO14
  - id: cam_i2c
    sda: GPIO25
    scl: GPIO23

# Timer Cam F camera config
esp32_camera:
  name: "${cam_label}"
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_id: cam_i2c
  data_pins: [GPIO32, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15
  vertical_flip: false
  horizontal_mirror: false
  resolution: 640x480
  jpeg_quality: 10

# RTC to keep time
time:
  - platform: bm8563
    i2c_id: bsp_i2c
    id: rtc_time

# Status LED (blue on-board, GPIO2)
output:
  - platform: ledc
    id: blue_led
    pin: GPIO2
  # Battery hold pin - MUST be HIGH for charging to work
  - platform: gpio
    id: batt_hold_pin
    pin: GPIO33

light:
  - platform: monochromatic
    output: blue_led
    name: "${led_label}"
    restore_mode: RESTORE_DEFAULT_ON

# Enable battery charging by holding GPIO33 HIGH
switch:
  - platform: output
    id: battery_hold
    internal: true
    output: batt_hold_pin
    restore_mode: ALWAYS_ON

sensor:
  # Battery monitoring via GPIO38 ADC
  # NOTE: When USB power connected, reads charging voltage (~4.1-4.2V)
  # Only shows true battery level when running on battery alone
  - platform: adc
    pin: GPIO38
    attenuation: 12dB
    id: battery_voltage
    internal: true
    update_interval: 300s
    filters:
      - multiply: 1.51

  - platform: template
    id: battery_percent
    name: "Battery %"
    unit_of_measurement: "%"
    device_class: battery
    accuracy_decimals: 0
    update_interval: 300s
    lambda: |-
      float v = id(battery_voltage).state;
      if (v <= 3.35) return 0.0;
      if (v >= 4.15) return 100.0;
      return (v - 3.35) / 0.80 * 100.0;
